# Generated by Django 3.1.1 on 2021-03-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Token', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
    ]
