# Generated by Django 3.1.1 on 2021-03-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210302_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
