# Generated by Django 3.1.1 on 2021-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_token_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creationTime',
            field=models.DateTimeField(default=True),
        ),
    ]
