# Generated by Django 3.1.1 on 2021-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210302_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
